Vagrant.configure("2")do|config|
  config.vm.box="centos/7"
  config.vm.hostname = "tp2"
  config.vm.network "private_network", ip: "192.168.2.11"
  
  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false 

  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  #Changement de la RAM
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  disk = './secondDisk.vdi'
  
  config.vm.provider "virtualbox" do |vb|
    unless File.exist?(disk)
      vb.customize ['createhd', '--filename',disk , '--variant', 'Fixed', '--size', 5 * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
    end

  # Ajout d'un nom à la VM
  config.vm.provider :virtualbox do |vb|
      vb.name = "tp2_linux"
  end

  # Exécution d'un script au démarrage de la VM
  config.vm.provision "shell", path: "script.sh"


end

