Vagrant.configure("2")do|config|
  config.vm.box="tp4-node1"

  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false 

  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "gitea" do |gitea|
    gitea.vm.network "private_network", ip: "192.168.1.41"
    gitea.vm.hostname = "gitea"
    gitea.vm.provision :shell, path: "./scriptstp4/up.sh"
    gitea.vm.provision :shell, path: "./scriptstp4/gitea/gitea.sh"
  end

  config.vm.define "mariadb" do |maria|
    maria.vm.network "private_network", ip: "192.168.1.42"
    maria.vm.hostname = "maria"
    maria.vm.provision :shell, path: "./scriptstp4/up.sh"
    maria.vm.provision :shell, path: "./scriptstp4/mariadb/mariadb.sh"
  end

  config.vm.define "nginx" do |nginx|
    nginx.vm.network "private_network", ip: "192.168.1.43"
    nginx.vm.hostname = "nginx"
    nginx.vm.provision :shell, path: "./scriptstp4/up.sh"
    nginx.vm.provision :shell, path: "./scriptstp4/nginx/nginx.sh"
  end


  config.vm.define "nfs" do |nfs|
    nfs.vm.network "private_network", ip: "192.168.1.44"
    nfs.vm.hostname = "nfs"
    nfs.vm.provision :shell, path: "./scriptstp4/up.sh"
    nfs.vm.provision :shell, path: "./scriptstp4/nfs/nfs.sh"
  end


end


